version: "3.7"

services:
  node1:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-node1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./data/node1:/cockroach/cockroach-data
    command: start-single-node --insecure --advertise-addr=node1
    networks:
      - cockroachdb-net

  node2:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-node2
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - ./data/node2:/cockroach/cockroach-data
    command: start --insecure --join=node1:26257 --advertise-addr=node2
    networks:
      - cockroachdb-net

networks:
  cockroachdb-net:
    driver: bridge
