version: "3.7"

services:
  node1:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-node1
    ports:
      - "26257:26257"
      - "3000:8080"
    volumes:
      - ./data/node1:/cockroach/cockroach-data
    command: start-single-node --insecure --advertise-addr=node1
    networks:
      - cockroachdb-net

  node2:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-node2
    ports:
      - "26258:26257"
      - "5101:8080"
    volumes:
      - ./data/node2:/cockroach/cockroach-data
    command: start --insecure --join=node1:26257 --advertise-addr=node2
    networks:
      - cockroachdb-net

  node3:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-node3
    ports:
      - "26259:26257"
      - "5100:8080"
    volumes:
      - ./data/node3:/cockroach/cockroach-data
    command: start --insecure --join=node1:26257 --advertise-addr=node3
    networks:
      - cockroachdb-net

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "5200:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - cockroachdb-net

networks:
  cockroachdb-net:
    driver: bridge
